/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/change-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Email Change
         * @description Подтверждение нового адреса.
         *
         *     Эндпоинт публичный: письмо открывают в том браузере, где почта, а не в том,
         *     где открыт кабинет. Операцию авторизует сам токен.
         */
        post: operations["confirm_email_change_api_auth_email_change_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram/miniapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login From Miniapp */
        post: operations["login_from_miniapp_api_auth_telegram_miniapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkey/login/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passkey Login Options */
        post: operations["passkey_login_options_api_auth_passkey_login_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkey/login/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passkey Login Verify */
        post: operations["passkey_login_verify_api_auth_passkey_login_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Methods */
        get: operations["auth_methods_api_auth_methods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Start */
        get: operations["telegram_start_api_auth_telegram_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/telegram/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Callback */
        get: operations["telegram_callback_api_auth_telegram_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Password */
        post: operations["set_password_api_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/email/change-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Email Change */
        post: operations["request_email_change_api_me_email_change_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_me_sessions_get"];
        put?: never;
        post?: never;
        /** Revoke Other Sessions */
        delete: operations["revoke_other_sessions_api_me_sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_api_me_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/passkeys/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passkey Registration Options */
        post: operations["passkey_registration_options_api_me_passkeys_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Passkeys */
        get: operations["list_passkeys_api_me_passkeys_get"];
        put?: never;
        /** Add Passkey */
        post: operations["add_passkey_api_me_passkeys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/passkeys/{passkey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Passkey */
        delete: operations["delete_passkey_api_me_passkeys__passkey_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/telegram/link-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Link Code */
        post: operations["issue_link_code_api_me_telegram_link_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink Telegram */
        delete: operations["unlink_telegram_api_me_telegram_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Gifts */
        get: operations["my_gifts_api_me_gifts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/gifts/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Gift */
        post: operations["redeem_gift_api_me_gifts_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_me_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_me_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_me_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description Витрина открыта без входа: до регистрации человеку не на что смотреть.
         */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Subscription
         * @description Подписки может не быть, и это не ошибка.
         *
         *     Пустой ответ со статусом 200 фронтенд отличает от отказа; 404 он вынужден
         *     был бы разбирать по коду, чтобы понять, показывать витрину или сообщение.
         */
        get: operations["my_subscription_api_me_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/subscription/auto-renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auto Renew */
        get: operations["get_auto_renew_api_me_subscription_auto_renew_get"];
        /** Set Auto Renew */
        put: operations["set_auto_renew_api_me_subscription_auto_renew_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/payment-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Payment Method */
        get: operations["my_payment_method_api_me_payment_method_get"];
        put?: never;
        post?: never;
        /**
         * Unlink Payment Method
         * @description Отвязывает карту; автоплатёж выключается вместе с ней.
         *
         *     Повтор не ошибка: у отсутствия карты и её удаления один и тот же
         *     наблюдаемый итог.
         */
        delete: operations["unlink_payment_method_api_me_payment_method_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/payment-method/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Card Binding
         * @description Начинает привязку карты без списания.
         */
        post: operations["start_card_binding_api_me_payment_method_bindings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/subscription/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Trial */
        post: operations["activate_trial_api_me_subscription_trial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Devices */
        get: operations["my_devices_api_me_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/devices/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlink Device */
        post: operations["unlink_device_api_me_devices_unlink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Traffic */
        get: operations["my_traffic_api_me_traffic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_admin_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/promos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Promos */
        get: operations["list_promos_api_admin_promos_get"];
        put?: never;
        /** Create Promo */
        post: operations["create_promo_api_admin_promos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/promos/{promo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate Promo */
        delete: operations["deactivate_promo_api_admin_promos__promo_id__delete"];
        options?: never;
        head?: never;
        /** Update Promo */
        patch: operations["update_promo_api_admin_promos__promo_id__patch"];
        trace?: never;
    };
    "/api/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description Все тарифы, включая скрытые и архивные: админ управляет и ими тоже.
         */
        get: operations["list_plans_api_admin_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_admin_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Archive Plan
         * @description Архивация, а не удаление: на тариф ссылаются подписки и журнал.
         */
        delete: operations["archive_plan_api_admin_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /** Update Plan */
        patch: operations["update_plan_api_admin_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/admin/remnawave/squads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Squads
         * @description Сквады читаются из панели, а не хранятся у нас: их состав меняет админ панели.
         */
        get: operations["list_squads_api_admin_remnawave_squads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Subscription
         * @description Начисление дней и смена тарифа руками админа.
         *
         *     Тело без days означает смену тарифа с конвертацией оплаченного остатка, с
         *     days — начисление указанного числа дней по этому тарифу. Разные действия
         *     разными полями, а не двумя маршрутами: решение принимает один и тот же
         *     человек в одной и той же форме.
         */
        post: operations["grant_subscription_api_admin_users__user_id__subscription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/refund-mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Order Refunded
         * @description Фиксирует выполненный у провайдера возврат, не трогая выданный доступ.
         */
        post: operations["mark_order_refunded_api_admin_orders__order_id__refund_mark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/compensations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compensate Order
         * @description Применяет ровно одну названную и идемпотентную местную коррекцию.
         */
        post: operations["compensate_order_api_admin_orders__order_id__compensations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/yookassa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yookassa Webhook
         * @description Принимает только идентификатор hint и сверяет платёж у YooKassa.
         */
        post: operations["yookassa_webhook_webhook_yookassa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/remnawave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remnawave Webhook */
        post: operations["remnawave_webhook_webhook_remnawave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedResponse */
        AcceptedResponse: {
            /** Status */
            status: string;
        };
        /**
         * AdminSubscriptionRequest
         * @description Начисление дней или смена тарифа админом.
         */
        AdminSubscriptionRequest: {
            /** Plan Id */
            plan_id: number;
            /** Days */
            days?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /**
         * AuthMethodsResponse
         * @description Какие способы входа показывать на экране входа.
         *
         *     Passkey поддерживает браузер, а не сервер, поэтому здесь он всегда true:
         *     решение принимает клиент. Telegram зависит от настроек развёртывания.
         */
        AuthMethodsResponse: {
            /** Telegram */
            telegram: boolean;
            /**
             * Passkey
             * @default true
             */
            passkey: boolean;
        };
        /** AutoRenewRequest */
        AutoRenewRequest: {
            /** Auto Renew Enabled */
            auto_renew_enabled: boolean;
        };
        /** AutoRenewResponse */
        AutoRenewResponse: {
            /** Auto Renew Enabled */
            auto_renew_enabled: boolean;
        };
        /**
         * CardBindingRequest
         * @description Откуда пользователь начал привязку — чтобы вернуть его туда же.
         */
        CardBindingRequest: {
            /**
             * Return Surface
             * @default web
             * @enum {string}
             */
            return_surface: "web" | "miniapp";
        };
        /**
         * CardBindingResponse
         * @description Адрес формы провайдера, где пользователь подтверждает карту.
         */
        CardBindingResponse: {
            /** Confirmation Url */
            confirmation_url: string | null;
        };
        /** ChangeEmailRequest */
        ChangeEmailRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * CompensationRequest
         * @description Одна необратимая местная коррекция, подтверждаемая отдельно.
         */
        CompensationRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "revoke_days" | "reverse_referral_reward";
            /** Idempotency Key */
            idempotency_key: string;
            /** Comment */
            comment: string;
        };
        /**
         * CreateOrderRequest
         * @description Только намерение покупателя; тариф и сумма всегда читаются сервером.
         */
        CreateOrderRequest: {
            /** Plan Id */
            plan_id: number;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "purchase" | "renew" | "gift";
            /**
             * Provider
             * @enum {string}
             */
            provider: "yookassa" | "stars";
            /** Promo Code */
            promo_code?: string | null;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Return Surface
             * @default web
             * @enum {string}
             */
            return_surface: "web" | "miniapp";
        };
        /** DeviceResponse */
        DeviceResponse: {
            /** Hwid */
            hwid: string;
            /** Platform */
            platform: string | null;
            /** Device Model */
            device_model: string | null;
            /** Os Version */
            os_version: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DevicesResponse */
        DevicesResponse: {
            /** Devices */
            devices: components["schemas"]["DeviceResponse"][];
            /** Limit */
            limit: number;
            /** Used */
            used: number;
        };
        /** EmailRequest */
        EmailRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** GiftVoucherResponse */
        GiftVoucherResponse: {
            /** Code */
            code: string;
            /**
             * Purchased At
             * Format: date-time
             */
            purchased_at: string;
            /** Redeemed At */
            redeemed_at: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Purchased By Me */
            purchased_by_me: boolean;
            /** Redeemed By Me */
            redeemed_by_me: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /** Valkey */
            valkey: boolean;
        };
        /**
         * LinkCodeResponse
         * @description Код привязки Telegram и готовая ссылка в чат бота.
         */
        LinkCodeResponse: {
            /** Code */
            code: string;
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string | null;
            /** Email Verified */
            email_verified: boolean;
            /** Telegram Username */
            telegram_username: string | null;
            /** Name */
            name: string | null;
            /**
             * Language
             * @enum {string}
             */
            language: "ru" | "en";
            /** Role */
            role: string;
            /** Referral Code */
            referral_code: string;
            /** Has Password */
            has_password: boolean;
            /** Has Telegram */
            has_telegram: boolean;
            /** Passkey Count */
            passkey_count: number;
        };
        /** MiniAppLoginRequest */
        MiniAppLoginRequest: {
            /** Init Data */
            init_data: string;
        };
        /**
         * OrderResponse
         * @description Без provider payload: клиенту достаточно снимка заказа и URL оплаты.
         */
        OrderResponse: {
            /** Id */
            id: number;
            /** Purpose */
            purpose: string;
            /** Plan Id */
            plan_id: number;
            /** Plan Code */
            plan_code: string;
            /** Plan Name */
            plan_name: {
                [key: string]: string;
            };
            /** Duration Days */
            duration_days: number;
            /** Price Rub */
            price_rub: string;
            /** Price Stars */
            price_stars: number;
            /** Gross Rub */
            gross_rub: string;
            /** Discount Rub */
            discount_rub: string;
            /** Amount Due Rub */
            amount_due_rub: string;
            /** Status */
            status: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Confirmation Url */
            confirmation_url: string | null;
            /**
             * Telegram Invoice Required
             * @default false
             */
            telegram_invoice_required: boolean;
            /** Telegram Handoff Url */
            telegram_handoff_url?: string | null;
        };
        /** PasskeyLoginRequest */
        PasskeyLoginRequest: {
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
        };
        /**
         * PasskeyOptionsResponse
         * @description Параметры WebAuthn как есть.
         *
         *     Структура задана спецификацией браузера и целиком уходит в
         *     `navigator.credentials`; описывать её своими моделями значит поддерживать
         *     копию чужого стандарта.
         */
        PasskeyOptionsResponse: {
            /** Options */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyRegisterRequest */
        PasskeyRegisterRequest: {
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** PasskeyResponse */
        PasskeyResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * PaymentMethodResponse
         * @description Действующая карта пользователя и доступность привязки без оплаты.
         */
        PaymentMethodResponse: {
            /** Title */
            title: string | null;
            /** Linked At */
            linked_at: string | null;
            /** Binding Available */
            binding_available: boolean;
        };
        /**
         * PlanRequest
         * @description Тариф, каким его заводит администратор.
         *
         *     Признака is_active здесь нет: тариф снимается с продажи архивацией через
         *     DELETE, а не переключением поля в форме редактирования.
         */
        PlanRequest: {
            /** Code */
            code: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Description */
            description?: {
                [key: string]: string;
            } | null;
            /** Duration Days */
            duration_days: number;
            /** Price Rub */
            price_rub: number | string;
            /** Price Stars */
            price_stars: number;
            /** Traffic Limit Bytes */
            traffic_limit_bytes: number;
            /**
             * Traffic Reset Strategy
             * @enum {string}
             */
            traffic_reset_strategy: "NO_RESET" | "DAY" | "WEEK" | "MONTH" | "MONTH_ROLLING";
            /** Hwid Device Limit */
            hwid_device_limit: number;
            /** Internal Squad Uuids */
            internal_squad_uuids: string[];
            /**
             * Is Trial
             * @default false
             */
            is_trial: boolean;
            /**
             * Is Visible
             * @default true
             */
            is_visible: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            } | null;
            /** Duration Days */
            duration_days: number;
            /** Price Rub */
            price_rub: string;
            /** Price Stars */
            price_stars: number;
            /** Traffic Limit Bytes */
            traffic_limit_bytes: number;
            /** Traffic Reset Strategy */
            traffic_reset_strategy: string;
            /** Hwid Device Limit */
            hwid_device_limit: number;
            /** Internal Squad Uuids */
            internal_squad_uuids: string[];
            /** Is Trial */
            is_trial: boolean;
            /** Is Active */
            is_active: boolean;
            /** Is Visible */
            is_visible: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** PromoRequest */
        PromoRequest: {
            /** Code */
            code: string;
            /**
             * Percent Off
             * @default 0
             */
            percent_off: number;
            /**
             * Bonus Days
             * @default 0
             */
            bonus_days: number;
            /** Max Uses */
            max_uses?: number | null;
            /** Per User Limit */
            per_user_limit?: number | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Starts At */
            starts_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** PromoResponse */
        PromoResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Percent Off */
            percent_off: number;
            /** Bonus Days */
            bonus_days: number;
            /** Max Uses */
            max_uses: number | null;
            /** Per User Limit */
            per_user_limit: number | null;
            /** Is Active */
            is_active: boolean;
            /** Starts At */
            starts_at: string | null;
            /** Expires At */
            expires_at: string | null;
        };
        /**
         * PublicPlanResponse
         * @description Тариф в витрине. Внутренние поля наружу не уезжают.
         *
         *     internal_squad_uuids не отдаётся: состав локаций — наша кухня, а не то,
         *     что клиент должен видеть в ответе API.
         */
        PublicPlanResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Description */
            description: {
                [key: string]: string;
            } | null;
            /** Duration Days */
            duration_days: number;
            /** Price Rub */
            price_rub: string;
            /** Price Stars */
            price_stars: number;
            /** Traffic Limit Bytes */
            traffic_limit_bytes: number;
            /** Hwid Device Limit */
            hwid_device_limit: number;
            /** Is Trial */
            is_trial: boolean;
        };
        /** RedeemGiftRequest */
        RedeemGiftRequest: {
            /** Code */
            code: string;
        };
        /**
         * RefundMarkRequest
         * @description Доказательство, что возврат у провайдера уже сделан человеком.
         */
        RefundMarkRequest: {
            /** Reference */
            reference: string;
            /** Comment */
            comment: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Language
             * @default ru
             * @enum {string}
             */
            language: "ru" | "en";
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Agent */
            user_agent: string | null;
            /** Ip */
            ip: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Current */
            is_current: boolean;
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Current Password */
            current_password?: string | null;
            /** New Password */
            new_password: string;
        };
        /** SquadResponse */
        SquadResponse: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
        };
        /** SubscriptionResponse */
        SubscriptionResponse: {
            /** Plan Code */
            plan_code: string;
            /** Plan Name */
            plan_name: {
                [key: string]: string;
            };
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Subscription Url */
            subscription_url: string | null;
            /** Traffic Limit Bytes */
            traffic_limit_bytes: number;
            /** Hwid Device Limit */
            hwid_device_limit: number;
            /** Auto Renew Enabled */
            auto_renew_enabled: boolean;
        };
        /**
         * SubscriptionStateResponse
         * @description Подписка вместе с правом на триал.
         *
         *     Одним ответом, а не двумя запросами: экран подписки решает по обоим полям
         *     сразу, показать срок или кнопку триала.
         */
        SubscriptionStateResponse: {
            subscription: components["schemas"]["SubscriptionResponse"] | null;
            /** Trial Available */
            trial_available: boolean;
        };
        /** TokenRequest */
        TokenRequest: {
            /** Token */
            token: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
        };
        /** TrafficDayResponse */
        TrafficDayResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Used Bytes */
            used_bytes: number;
        };
        /** TrafficResponse */
        TrafficResponse: {
            /** Used Bytes */
            used_bytes: number;
            /** Lifetime Bytes */
            lifetime_bytes: number;
            /** Limit Bytes */
            limit_bytes: number;
            /** Days */
            days: components["schemas"]["TrafficDayResponse"][];
        };
        /** UnlinkDeviceRequest */
        UnlinkDeviceRequest: {
            /** Hwid */
            hwid: string;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Name */
            name?: string | null;
            /**
             * Language
             * @enum {string}
             */
            language: "ru" | "en";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoAmIResponse */
        WhoAmIResponse: {
            /** Id */
            id: number;
            /** Role */
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Отказала хотя бы одна зависимость */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password_api_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_email_change_api_auth_email_change_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_from_miniapp_api_auth_telegram_miniapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MiniAppLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    passkey_login_options_api_auth_passkey_login_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyOptionsResponse"];
                };
            };
        };
    };
    passkey_login_verify_api_auth_passkey_login_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_methods_api_auth_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethodsResponse"];
                };
            };
        };
    };
    telegram_start_api_auth_telegram_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    telegram_callback_api_auth_telegram_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_email_change_api_me_email_change_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_me_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    revoke_other_sessions_api_me_sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_session_api_me_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    passkey_registration_options_api_me_passkeys_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyOptionsResponse"];
                };
            };
        };
    };
    list_passkeys_api_me_passkeys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyResponse"][];
                };
            };
        };
    };
    add_passkey_api_me_passkeys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_passkey_api_me_passkeys__passkey_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passkey_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_link_code_api_me_telegram_link_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkCodeResponse"];
                };
            };
        };
    };
    unlink_telegram_api_me_telegram_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_gifts_api_me_gifts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftVoucherResponse"][];
                };
            };
        };
    };
    redeem_gift_api_me_gifts_redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemGiftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_me_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
        };
    };
    create_order_api_me_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_me_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPlanResponse"][];
                };
            };
        };
    };
    my_subscription_api_me_subscription_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStateResponse"];
                };
            };
        };
    };
    get_auto_renew_api_me_subscription_auto_renew_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoRenewResponse"];
                };
            };
        };
    };
    set_auto_renew_api_me_subscription_auto_renew_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoRenewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoRenewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_payment_method_api_me_payment_method_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodResponse"];
                };
            };
        };
    };
    unlink_payment_method_api_me_payment_method_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_card_binding_api_me_payment_method_bindings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardBindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBindingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_trial_api_me_subscription_trial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStateResponse"];
                };
            };
        };
    };
    my_devices_api_me_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesResponse"];
                };
            };
        };
    };
    unlink_device_api_me_devices_unlink_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlinkDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_traffic_api_me_traffic_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficResponse"];
                };
            };
        };
    };
    whoami_api_admin_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
        };
    };
    list_promos_api_admin_promos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoResponse"][];
                };
            };
        };
    };
    create_promo_api_admin_promos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_promo_api_admin_promos__promo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_promo_api_admin_promos__promo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_admin_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"][];
                };
            };
        };
    };
    create_plan_api_admin_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_plan_api_admin_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_admin_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_squads_api_admin_remnawave_squads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadResponse"][];
                };
            };
        };
    };
    grant_subscription_api_admin_users__user_id__subscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_order_refunded_api_admin_orders__order_id__refund_mark_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundMarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compensate_order_api_admin_orders__order_id__compensations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompensationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yookassa_webhook_webhook_yookassa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remnawave_webhook_webhook_remnawave_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
